### ISSUE TITLE
Bump seems to be infinite

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/graph_weather#120]
Bump is continually autobumping the package and releasing new images every few minutes it seems? Not sure if other packages are seeing this too or not. @peterdudfield @Sukh-P

**Comment by peterdudfield** [comment]
Thanks @jacobbieker

**Comment by peterdudfield** [comment]
We need to put `message = Bump version: {current_version} → {new_version} [skip ci]` in the bump file
