### ISSUE TITLE
[Question] Where are the constants coming from?

### ISSUE THREAD

**Issue by marvingabler** [openclimatefix/graph_weather#28]
If I'm blind I'm sorry, but currently I can not find a source (in paper or Readme) regarding the constants in [graph_weather](https://github.com/openclimatefix/graph_weather)/[graph_weather](https://github.com/openclimatefix/graph_weather/tree/main/graph_weather)/[data](https://github.com/openclimatefix/graph_weather/tree/main/graph_weather/data)/const.py , where are they coming from / calculated from exactly?

Great work btw

**Comment by jacobbieker** [comment]
Hi,

As in the paper, the constants are taken from 100 random timesteps in the GFS v16 fprecasts dataset that is here: https://huggingface.co/datasets/openclimatefix/gfs-reforecast at the 0.25 resolution.

**Comment by jacobbieker** [comment]
I also plan on doing it for ERA5 Reanalysis data, once I have more data uploaded to here https://huggingface.co/datasets/openclimatefix/era5

**Comment by marvingabler** [comment]
Thanks for the explanation Jacob!
