### ISSUE TITLE
Missing dependencies in setup.py ?

### ISSUE THREAD

**Issue by paapu88** [openclimatefix/graph_weather#33]
Dear Developers,
I installed graph_weather from source (from the main branch) using
`pip install -e .` in the main directory (directory graph_weather, where the setup.py lives).

I wanted to do some training, but before that I needed to install additional dependencies:
```
pip install pytorch-lightning
pip install pysolar
pip install torch-geometric
pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+cu102.html
```
In the last one check correct pytorch + cuda/cpu combination from https://pypi.org/project/torch-sparse/
(I had pytorch 1.12 and cu102 (I had gpu with CUDA 10.2) )

With these additions I got `python3 graph_weather/train/pl_graph_weather.py` going.

Terveisin, Markus

**Comment by jacobbieker** [comment]
Oh yeah, the easiest method right now to run graph_weather is to use conda and use ```conda env create -f environment.yml``` from the base of the repo, as it will install those dependencies. I had trouble getting the different torch-geometric to install correctly with pip before, but glad you were able to!
