### ISSUE TITLE
Keisler code?

### ISSUE THREAD

**Issue by paapu88** [openclimatefix/graph_weather#34]
- Is the original Keisler code for available somewhere (the code that produced https://arxiv.org/abs/2202.07575 results)?
- Has Keisler anyhing to do with this project? Is he willing to help?

**Comment by jacobbieker** [comment]
As far as I know, the original code and data is not available, I asked him about it on Twitter soon after the paper was released, and he said he didn't have plans at that time to release the code. He said he used Jax, and Jraph to make the model though.

He doesn't have anything to do with this model, this is just a reimplementation/extension of his paper

**Comment by paapu88** [comment]
Thanks for info!
