### ISSUE TITLE
Model(features) Error

### ISSUE THREAD

**Issue by taeyoon91** [openclimatefix/graph_weather#48]
I succeeded to install graph-weather by pip

But I got an error message for **model(features)**

Message:
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 78 but got size 102 for tensor number 1 in the list.

I checked feature shape -> torch.Size([2, 64800, 78])

I don't know why the input feature got 102 tensor.. anyone who help me?

**Comment by jacobbieker** [comment]
Hi, yes, by default there is the `aux_dim` which is set to 24, if you set that to 0 then it will work. The `aux_dim` is, in the paper, the extra inputs that aren't forecasted, such as the sun irradiance, land/sea mask, etc.
