### ISSUE TITLE
Memory optimization in graph data

### ISSUE THREAD

**Issue by najeeb-kazmi** [openclimatefix/graph_weather#71]
Not a bug, but seemed like the best issue template to use :)

Passing `x` is unnecessary here as it is never accessed. The `nodes` tensor does not need to be created. Could save a bit of memory here that's allocated to it.
https://github.com/openclimatefix/graph_weather/blob/ef13589651da5491ddaf7570d788c15621b4d0bb/graph_weather/models/layers/encoder.py#L107

Here also.
https://github.com/openclimatefix/graph_weather/blob/ef13589651da5491ddaf7570d788c15621b4d0bb/graph_weather/models/layers/assimilator_decoder.py#L104

And here.
https://github.com/openclimatefix/graph_weather/blob/ef13589651da5491ddaf7570d788c15621b4d0bb/graph_weather/models/layers/assimilator_encoder.py#L216

**Comment by jacobbieker** [comment]
Ah cool, thanks for pointing that out!
