### ISSUE TITLE
Error while running the `run_full.py` for the gfs-reforecast dataset from hugging face

### ISSUE THREAD

**Issue by SwordSaintLancelot** [openclimatefix/graph_weather#74]
## Describe the bug
While running and debugging the python file mentioned, I found that the data is sliced for only one time stamp whereas in the next lines it is mentioned that the data has a starting and ending time. After reading through the paper, my understanding is that one node has one timestamp and model is trained only be of one timestamp but that contradicts the `start` and `end` variables in the XrDataset dataloader.
![image](https://github.com/openclimatefix/graph_weather/assets/34275219/9aa9ebaf-df7b-4ecd-a0bb-20f336bbcd05)

I do have another question regarding the aux_dims in the encoder. If I run the example usage, it shows the issue that output and input dimensions do not match as input feature dimensions sum up to a total of 102 (input_dims(78) + aux_dim(24)) whereas the output dims are just 78.
![image](https://github.com/openclimatefix/graph_weather/assets/34275219/22da16df-f5e7-442f-bf9e-429b4b06ff89)

## To Reproduce
1. Go to hf_forecasts.json.
2. Change the first file name to `data/forecasts/GFSv16/2021/04/2021040100.zarr.zip` as other files are not found on the webpage
3. Go to train/run_full.py
4. Run the file.
5. See error

1. Go to train.
2. Create a new file for example usage.
3. Run the file.
6. See error

## Expected behavior
These steps should give you the errors as shown in the images.

## Additional context
Also, I could not find the files mentioned in the hf_forecasts.json on hugging face gfs-reforecast dataset.

**Comment by jjjj32481** [comment]
Replacing the line 35, i.e., "data = self.data.isel(reftime=item, time=slice(start_idx, start_idx + 1))", in XrDataset definition with the following line maybe effective.
data = self.data.isel(reftime=item, time=slice(start_idx, start_idx + 2))

**Comment by SwordSaintLancelot** [comment]
Thank you for the response. I have already implemented this line and have tested running the model and it works. I just wanted to make sure, if this indeed is an error, it might be better to correct this in the main repo as well.

**Comment by peterdudfield** [comment]
Thanks @jjjj32481 and @SwordSaintLancelot would you be able to do a PR? 

@jjjj32481 do you know why this is?

**Comment by SwordSaintLancelot** [comment]
@peterdudfield I don't think I have write access to the repository. Should I still look into creating the PR?

**Comment by peterdudfield** [comment]
Yea, I think you can fork the repo, and then make a PR back to this one?
