### ISSUE TITLE
Error in the example 

### ISSUE THREAD

**Issue by ammoniaca** [openclimatefix/graph_weather#83]
## Describe the bug
[RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 78 but got size 102 for tensor number 1 in the list](https://stackoverflow.com/questions/77861879/runtimeerror-sizes-of-tensors-must-match-except-in-dimension-1-expected-size-7)

## To Reproduce
Just the example in the main page

import torch
from graph_weather import GraphWeatherForecaster
from graph_weather.models.losses import NormalizedMSELoss

lat_lons = []
for lat in range(-90, 90, 1):
    for lon in range(0, 360, 1):
        lat_lons.append((lat, lon))
model = GraphWeatherForecaster(lat_lons)

features = torch.randn((2, len(lat_lons), 78))

out = model(features)
criterion = NormalizedMSELoss(lat_lons=lat_lons, feature_variance=torch.randn((78,)))
loss = criterion(out, features)
loss.backward()

## Additional context
when I hit the line out = model(features) I got the error message

**Comment by MadJokkerr** [comment]
@ammoniaca if this task is complete can you please close this issue
