### ISSUE TITLE
Fix test workflow GitHub Action

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/graph_weather#88]
## Describe the bug
The test GitHub Action workflow is failing on installing PyTorch or PyTorch Geometric.

## To Reproduce
Look at the Actions tab of the repo, and the failed test runs.

## Expected behavior
PyTorch and PyTorch Geometric should be installed successfully so that the tests can run.

## Additional context
We also want to keep up with the latest PyTorch Geometic/PyTorch/Python versions.

**Comment by aavashsubedi** [comment]
Hi, so there's currently no support for 2.0.0/2.1.0 for torch on Python 3.12 and this appears to be the test that's failing. Is it alright to skip these combinations on the workflow.yaml until Torch releases it? https://github.com/pytorch/pytorch/issues/110436 (also nothing here too: https://download.pytorch.org/whl/torch/)

**Comment by aavashsubedi** [comment]
@jacobbieker  #89

**Comment by jacobbieker** [comment]
Awesome! Thanks for this! Fixed in #89
