### ISSUE TITLE
test_normalized_loss fails

### ISSUE THREAD

**Issue by rahul-maurya11b** [openclimatefix/graph_weather#96]
## To Reproduce

run pytest

## Expected behavior

![image](https://github.com/openclimatefix/graph_weather/assets/98907006/98171623-248c-4667-b842-41d20077fea0)

and if I remove the optional normalize then another error: 

![image](https://github.com/openclimatefix/graph_weather/assets/98907006/29b02c25-9ba8-45c6-8223-08292d62cc80)

what is the issue ??

**Comment by rahul-maurya11b** [comment]
@jacobbieker  sir, what can be the issue here ??

**Comment by gbruno16** [comment]
Hi @rahul-maurya11b! Can you check if your file `graph_weather/models/losses.py` is the same as the current version? In particular the normalization flag in:
https://github.com/openclimatefix/graph_weather/blob/084c5ab7099c3f0c663f3f1257c043e2901308c6/graph_weather/models/losses.py#L10C4-L12C7

**Comment by gbruno16** [comment]
I've tried running the tests on my end, but surprisingly, it looks like I can't reproduce the issue:
<img width="590" alt="test" src="https://github.com/openclimatefix/graph_weather/assets/72879691/faaf6868-45cd-4413-a709-55da8d11ce15">

Could you provide any additional details or steps to help me understand better?

**Comment by rahul-maurya11b** [comment]
is it because of differences in plugins and versions? 
![image](https://github.com/openclimatefix/graph_weather/assets/98907006/725d2214-fdea-4606-813d-c961f71076dc)
can you describe your steps on how you build it?

**Comment by gbruno16** [comment]
Yes, of course! I am following these steps:
- clone the repository: `git clone https://github.com/openclimatefix/graph_weather.git`
- install the requirements: `pip install -r requirements.txt`
- run `python -m pytest`

My computer has not enough ram to run tests locally, so I just use google colab. To reproduce my tests you can check: https://colab.research.google.com/drive/1OlKCIibSvCU3g4x8Pjz8tgqQSmJmsrAx?usp=drive_link.

**Comment by rahul-maurya11b** [comment]
Thanks, I will delete and again install the requirements. I will update you.

**Comment by rahul-maurya11b** [comment]
hi @gbruno16 thanks done with the setup issue was with my virtual env it was taking packages from the cache.
now all tests pass but getting warnings it's because of different versions.
![image](https://github.com/openclimatefix/graph_weather/assets/98907006/70bfab64-a672-4b4c-a583-41f1431cf23d)

**Comment by rahul-maurya11b** [comment]
hi @gbruno16 have you tried building it using docker?
I want to replicate the same environment but getting this error : 

 ```
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

ERROR conda.cli.main_run:execute(124): `conda run python -u train/pl_graph_weather.py --gpus 16 --hidden 64 --num-blocks 3 --batch 16` failed. (See above for error)
```

@jacobbieker  sir is it like we need to have Cuda installed on docker ??, bcz I got this error after building the docker image and then running it with no changes compared to the current repo.

**Comment by jacobbieker** [comment]
Hi, yes, by default this assumes Cuda is available. A great contribution would to add a docker container that works without Cuda as well, if you'd be interested in adding it? Or update the requirements to not require Cuda, although we do want it to install the cuda versions if cuda is available 

Also, thanks @gbruno16 for helping debug this!

**Comment by rahul-maurya11b** [comment]
@jacobbieker yes, sir, I am interested. I have started working on it.  should I create an issue that you can assign me?

**Comment by jacobbieker** [comment]
Yep! Sounds good

**Comment by rahul-maurya11b** [comment]
@jacobbieker sir  issue created created please check #97
